---
- name: Install Orthanc locally with Docker
  hosts: local
  become: true

  tasks:
    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: true

    - name: Make sure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
